"""change of user model

Revision ID: 49536421c78c
Revises: a9e7c81cc043
Create Date: 2021-08-30 01:36:02.555942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49536421c78c'
down_revision = 'a9e7c81cc043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
